### ISSUE TITLE
Can't add git_hooks config to project if no config

### ISSUE THREAD

**Issue by garthk** [TheFirstAvenger/ironman#23]
My project doesn't have a `config` directory, so:

```
Add git_hooks config to project? [Yn] y
** (FunctionClauseError) no function clause matching in Regex.match?/2    
    
    The following arguments were given to Regex.match?/2:
    
        # 1
        ~r/#\s+import_config "\\#{Mix.env\(\)}.exs"/
    
        # 2
        nil
    
    Attempted function clauses (showing 1 out of 1):
    
        def match?(%Regex{} = regex, string) when is_binary(string)
    
    (elixir) lib/regex.ex:268: Regex.match?/2
    lib/ironman/checks/git_hooks_config.ex:46: Ironman.Checks.GitHooksConfig.set_config_exs/1
    lib/ironman/checks/git_hooks_config.ex:34: Ironman.Checks.GitHooksConfig.do_add_config/1
    lib/ironman/runner.ex:68: Ironman.Runner.run_check/2
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/ironman/runner.ex:28: Ironman.Runner.run/0
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
```

Workaround: `mkdir config && echo "import Config" > config/config.exs`

**Comment by garthk** [comment]
Ha! `suit_up` added `dev.exs`, `prod.exs`, and `test.exs` but didn't add a line to `config.exs` to import them e.g. for Elixir 1.9:

```elixir
import_config "#{Mix.env()}.exs"
```
